spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rootconnect
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: my-super-secret-jwt-key-which-is-at-least-32-characters
  expiration: 3600000
